#!/bin/bash

func write_iptables () {
mkdir /var/lib/jd-iptables/ -p

nic_name=$(ip link show|grep -i "state UP"|awk -F: '{print $2}'|head -1)
cat >  /var/lib/jd-iptables/snat.rules << EOF
# Generated by iptables-save v1.4.21 on Fri Jan  6 13:07:39 2017
*raw
:PREROUTING ACCEPT [6413:538692]
:OUTPUT ACCEPT [36:2968]
COMMIT
# Completed on Fri Jan  6 13:07:39 2017
# Generated by iptables-save v1.4.21 on Fri Jan  6 13:07:39 2017
*mangle
:PREROUTING ACCEPT [6413:538692]
:INPUT ACCEPT [16:1344]
:FORWARD ACCEPT [6397:537348]
:OUTPUT ACCEPT [36:2968]
:POSTROUTING ACCEPT [6433:540316]
COMMIT
# Completed on Fri Jan  6 13:07:39 2017
# Generated by iptables-save v1.4.21 on Fri Jan  6 13:07:39 2017
*filter
:INPUT ACCEPT [16:1344]
:FORWARD ACCEPT [6397:537348]
:OUTPUT ACCEPT [36:2968]
COMMIT
# Completed on Fri Jan  6 13:07:39 2017
# Generated by iptables-save v1.4.21 on Fri Jan  6 13:07:39 2017
*nat
:PREROUTING ACCEPT [5:420]
:INPUT ACCEPT [2:168]
:OUTPUT ACCEPT [10:812]
:POSTROUTING ACCEPT [0:0]
-A POSTROUTING -s 192.168.0.0/24  -o $nic_name -j MASQUERADE
-A POSTROUTING -s 10.0.0.0/8 -o $nic_name -j MASQUERADE
-A POSTROUTING -s 172.16.0.0/16 -o $nic_name -j MASQUERADE
COMMIT
# Completed on Fri Jan  6 13:07:39 2017
EOF
}
