#!/bin/bash

curTime=`date '+%Y-%m-%d %H:%M:%S'`

function param_optimalize () {
PARAMS="
net.ipv4.ip_forward=1
net.netfilter.nf_conntrack_max=2000000
net.netfilter.nf_conntrack_buckets=500000
net.netfilter.nf_conntrack_tcp_timeout_established=7500
"

for P in $PARAMS
do
    sysctl -w $P > /dev/null
    sed -i "/$P/d" /etc/sysctl.conf
    echo "$P" >> /etc/sysctl.conf
done

sysctl -p
}

function write_iptables () {

nic_name=$(ip link show|grep -i "state UP"|awk -F: '{print $2}'|head -1)
if [ -z ${nic_name} ]; then
    echo "$curTime snat write_iptables Error, nic_name is NULL" | tee  /var/log/messages
    return
fi

echo "====================================================="
echo "     SNAT nic name is $nic_name"
echo "====================================================="
cat >  /var/lib/jd-iptables/snat.rules << EOF
# Generated by iptables-save v1.4.21 on Fri Jan  6 13:07:39 2017
*raw
:PREROUTING ACCEPT [6413:538692]
:OUTPUT ACCEPT [36:2968]
COMMIT
# Completed on Fri Jan  6 13:07:39 2017
# Generated by iptables-save v1.4.21 on Fri Jan  6 13:07:39 2017
*mangle
:PREROUTING ACCEPT [6413:538692]
:INPUT ACCEPT [16:1344]
:FORWARD ACCEPT [6397:537348]
:OUTPUT ACCEPT [36:2968]
:POSTROUTING ACCEPT [6433:540316]
COMMIT
# Completed on Fri Jan  6 13:07:39 2017
# Generated by iptables-save v1.4.21 on Fri Jan  6 13:07:39 2017
*filter
:INPUT ACCEPT [16:1344]
:FORWARD ACCEPT [6397:537348]
:OUTPUT ACCEPT [36:2968]
COMMIT
# Completed on Fri Jan  6 13:07:39 2017
# Generated by iptables-save v1.4.21 on Fri Jan  6 13:07:39 2017
*nat
:PREROUTING ACCEPT [5:420]
:INPUT ACCEPT [2:168]
:OUTPUT ACCEPT [10:812]
:POSTROUTING ACCEPT [0:0]
-A POSTROUTING -s 192.168.0.0/16 -o $nic_name -j MASQUERADE
-A POSTROUTING -s 10.0.0.0/8 -o $nic_name -j MASQUERADE
-A POSTROUTING -s 172.16.0.0/12 -o $nic_name -j MASQUERADE
COMMIT
# Completed on Fri Jan  6 13:07:39 2017
EOF
echo "$curTime snat write_iptables OK" | tee /var/log/messages
}

yum install iptables iptables-services -y

systemctl enable iptables && systemctl start iptables

mkdir /var/lib/jd-iptables/ -p
write_iptables

param_optimalize

echo 500000 > /sys/module/nf_conntrack/parameters/hashsize

sed -i "/nf_conntrack hashsize/d"  /etc/modprobe.d/iptables.conf > /dev/null 2>&1
echo "options nf_conntrack hashsize=500000"  >> /etc/modprobe.d/iptables.conf

sed -i "/hashsize/d" /etc/rc.d/rc.local
echo "echo 500000 > /sys/module/nf_conntrack/parameters/hashsize"  >> /etc/rc.d/rc.local

cat /var/lib/jd-iptables/snat.rules > /etc/sysconfig/iptables

iptables-restore /var/lib/jd-iptables/snat.rules

cat /etc/sysconfig/iptables

