#!/bin/sh
#
# ustack-doctor UnitedStack Doctor Service
#
# chkconfig:   - 98 02
# description: At the heart of the cloud framework is an API Server. \
#              This API Server makes command and control of the      \
#              hypervisor, storage, and networking programmatically  \
#              available to users in realization of the definition   \
#              of cloud computing.

### BEGIN INIT INFO
# Provides:
# Required-Start: $remote_fs $network $syslog
# Required-Stop: $remote_fs $syslog
# Default-Stop: 0 1 6
# Short-Description: UnitedStack Doctor Service
# Description: At the heart of the cloud framework is an API Server.
#              This API Server makes command and control of the
#              hypervisor, storage, and networking programmatically
#              available to users in realization of the definition
#              of cloud computing.
### END INIT INFO

. /etc/rc.d/init.d/functions
suffix=api
exec="/usr/bin/doctor-$suffix"

command=$1
what=$2

help() {
   echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload} {region|all} "
}

if [ -z "$command" ]; then
    help
    exit 1
fi

if [ -z "$what" ]; then
    help
    exit 1
fi

if [ "$what" == "all" ]; then
    what=""
    for region in `find -L /etc/doctor/ -mindepth 1 -maxdepth 1 -type f -printf '%f\n' | egrep "conf$" | awk -F'.' '{print $1}'`
    do
        what="$what $region"
    done
fi

start() {
    [ -x $exec ] || exit 5
    [ -f $config ] || exit 6
    echo -n $"Starting $prog: "
    daemon --user root --pidfile $pidfile "$exec --config-file $config --logfile $logfile &>/dev/null & echo \$! > $pidfile"
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
}

stop() {
    echo -n $"Stopping $prog: "
    killproc -p $pidfile $prog
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
}

restart() {
    stop
    start
}

reload() {
    restart
}

force_reload() {
    restart
}

rh_status() {
    status -p $pidfile $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


for target in $what
do
    prog=ustack-doctor-$suffix-$target
    config="/etc/doctor/${target}.conf"
    pidfile="/var/run/doctor/doctor-$suffix-$target.pid"
    logfile="/var/log/doctor/$suffix-$target.log"
    lockfile=/var/lock/subsys/$prog

    case "$command" in
        start)
            rh_status_q && exit 0
            $command
            ;;
        stop)
            rh_status_q || exit 0
            $command
            ;;
        restart)
            $command
            ;;
        reload)
            rh_status_q || exit 7
            $command
            ;;
        force-reload)
            force_reload
            ;;
        status)
            rh_status
            ;;
        condrestart|try-restart)
            rh_status_q || exit 0
            restart
            ;;
        *)
            help
            exit 2
    esac
done

exit $?
